# Generated by Django 4.1.5 on 2023-01-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
