# Generated by Django 4.1.5 on 2023-01-17 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interaction',
            unique_together={('user_id', 'content_id', 'interaction_type')},
        ),
    ]
